server:
    error:
        include-binding-errors: always
        include-message: always
    port: 8086

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: OCB318017@
        url: jdbc:mysql://localhost:3306/shopApp
    jpa:
        generate-ddl: 'true'
        properties:
            hibernate:
                #        enable_lazy_load_no_trans: update
                ddl-auto: update
        show-sql: false
        database-platform: org.hibernate.dialect.MySQL5Dialect
    mail:
        host: smtp.gmail.com
        username: hoangOCB0409@gmail.com
        password: kfblirmbraoxkevs
        port: 25
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
