spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: OCB318017@
    url: jdbc:mysql://localhost:3306/shopApp
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
#        enable_lazy_load_no_trans: update
        ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  error:
    include-binding-errors: always
    include-message: always
  port: 8086
